//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Console.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Console.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Advent of Code 2020&lt;/title&gt;
        ///    &lt;!--[if lt IE 9]&gt;&lt;script src=&quot;/static/html5.js&quot;&gt;&lt;/script&gt;&lt;![endif]--&gt;
        ///    &lt;link href=&apos;//fonts.googleapis.com/css?family=Source+Code+Pro:300&amp;subset=latin,latin-ext&apos; rel=&apos;stylesheet&apos;
        ///        type=&apos;text/css&apos; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/static/style.css?28&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet alternate&quot; type=&quot;text/css&quot; href=&quot;/static/highcontrast.css?0&quot; title=&quot;High Contr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CalendarPage {
            get {
                return ResourceManager.GetString("CalendarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0035)https://adventofcode.com/2021/day/8 --&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///    &lt;title&gt;Day 8 - Advent of Code 2021&lt;/title&gt;
        ///    &lt;!--[if lt IE 9]&gt;&lt;script src=&quot;/static/html5.js&quot;&gt;&lt;/script&gt;&lt;![endif]--&gt;
        ///    &lt;link href=&quot;./Day 8 - Advent of Code 2021_files/css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./Day 8 - Advent of Code 2021_files/style.css&quot;&gt;
        ///    &lt;link r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompleteDayPage {
            get {
                return ResourceManager.GetString("CompleteDayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0035)https://adventofcode.com/2021/day/9 --&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///&lt;title&gt;Day 9 - Advent of Code 2021&lt;/title&gt;
        ///&lt;!--[if lt IE 9]&gt;&lt;script src=&quot;/static/html5.js&quot;&gt;&lt;/script&gt;&lt;![endif]--&gt;
        ///&lt;link href=&quot;./Day 9 - Advent of Code 2021_files/css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./Day 9 - Advent of Code 2021_files/style.css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet alternate&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotStartedDayPage {
            get {
                return ResourceManager.GetString("NotStartedDayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0035)https://adventofcode.com/2021/day/1 --&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///    &lt;title&gt;Day 1 - Advent of Code 2021&lt;/title&gt;
        ///    &lt;!--[if lt IE 9]&gt;&lt;script src=&quot;/static/html5.js&quot;&gt;&lt;/script&gt;&lt;![endif]--&gt;
        ///    &lt;link href=&quot;./VeryCompleteDayPage_files/css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./VeryCompleteDayPage_files/style.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VeryCompleteDayPage {
            get {
                return ResourceManager.GetString("VeryCompleteDayPage", resourceCulture);
            }
        }
    }
}
