//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109
        ///117
        ///118
        ///98
        ///102
        ///94
        ///101
        ///109
        ///121
        ///126
        ///117
        ///116
        ///134
        ///119
        ///98
        ///97
        ///96
        ///98
        ///101
        ///107
        ///123
        ///134
        ///137
        ///160
        ///171
        ///188
        ///189
        ///188
        ///169
        ///163
        ///182
        ///184
        ///187
        ///184
        ///196
        ///199
        ///218
        ///222
        ///223
        ///218
        ///214
        ///220
        ///215
        ///223
        ///226
        ///228
        ///236
        ///237
        ///268
        ///277
        ///282
        ///284
        ///285
        ///288
        ///289
        ///313
        ///322
        ///331
        ///335
        ///331
        ///316
        ///323
        ///314
        ///313
        ///314
        ///301
        ///302
        ///320
        ///315
        ///323
        ///324
        ///346
        ///347
        ///362
        ///376
        ///377
        ///378
        ///379
        ///381
        ///391
        ///392
        ///395
        ///391
        ///393
        ///399
        ///401
        ///403
        ///428
        ///423
        ///422
        ///427
        ///430
        ///432
        ///431
        ///433
        ///449
        ///456
        ///455
        ///456
        ///457
        ///456
        ///460
        ///461
        ///460 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOfCode2021_Challenges_SonarSweep {
            get {
                return ResourceManager.GetString("AdventOfCode2021.Challenges.SonarSweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199
        ///200
        ///208
        ///210
        ///200
        ///207
        ///240
        ///269
        ///260
        ///263.
        /// </summary>
        internal static string AdventOfCode2021_Challenges_SonarSweepTest {
            get {
                return ResourceManager.GetString("AdventOfCode2021.Challenges.SonarSweepTest", resourceCulture);
            }
        }
    }
}
